In [16]:
import torch

- create a tensor an set requires_grad=True to track computation with it

In [17]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


- Do a tensor operation

In [18]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y was creaed as a result of an operation,so it has grad_fn

In [19]:
print(y.grad_fn)

Do more operations on y

In [20]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [21]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## Gradients
out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.))

In [22]:
out.backward()

In [23]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [24]:
x = torch.randn(3,requires_grad=True)

y = x*2
while y.data.norm() < 10:
    y = y*2
    
print(y)

tensor([-14.0376,  -8.4605,   5.2395], grad_fn=<MulBackward0>)


in this case y is no longer a scalar. torch.autograd couuld not compute the full jacobian directly, but if we just want the vector-jacobian product,simply pass the vector to backward as argument

In [25]:
v = torch.tensor([1.0,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([8.0000e+00, 8.0000e+00, 8.0000e-04])


In [28]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


by using ```.detch()``` to get a new Tensor with the dame content but that does not require gradients

In [30]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
