- 创建ndarray

In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

- 嵌套序列转换成多维数组

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
# dtype
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int64')

- zeros/ones/empty

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.empty((2,3,3)) # 没有任何具体值的数组

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

- arange对应python内置的range

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- ndarray的数据类型
- dtype是NumPy强大和灵活的原因之一

In [14]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


- astype

In [15]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [18]:
arr = np.array([3.7,-1,2,3.2])
arr

array([ 3.7, -1. ,  2. ,  3.2])

In [19]:
arr.astype(np.int32)

array([ 3, -1,  2,  3], dtype=int32)

In [20]:
numeric_strings = np.array(['1.2','34.32','1.34'],dtype=np.string_)
numeric_strings.astype(float)

array([ 1.2 , 34.32,  1.34])

In [21]:
int_array = np.arange(10)
calibers = np.array([.22,.240,.234,.33,.23],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
empty_unit32 = np.empty(8,dtype='u4')
empty_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [23]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])